### ISSUE TITLE
Test status on Windows

### ISSUE THREAD

**Issue by gasuperdev** [GeoscienceAustralia/PyRate#12]
At 97e6e02d26108fe192d92e4cee100fb96e502502 I get the following output when running on Windows (on my laptop as I can't install the required packages on my desktop). I've not pursued this beyond what I've reported below, as I'm not sure we care about windows:

```
Usage: nosetests-script.py [options] DEM-HEADER GAMMA_FILE [GAMMA_FILE...]

nosetests-script.py: error: Usage: %prog [options] DEM-HEADER GAMMA_FILE [GAMMA_FILE...]
EUsage: nosetests-script.py [options] ROIPAC_FILE [ROIPAC_FILE...]

nosetests-script.py: error: Usage: %prog [options] ROIPAC_FILE [ROIPAC_FILE...]
E...........................................d:\code\mycode\python\PyRate\pyrate\tests\orbital_tests.py:193: RuntimeWarning: invalid value encountered in not_equal
  self.assertTrue(c.ptp() != 0) # ensure range of values in grid
........................................E....E.....E.....F...................E................E..................
======================================================================
ERROR: test_with_gamma (pyrate.tests.system.system_test.SystemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\system\system_test.py", line 16, in test_with_gamma
    gamma.main()
  File "d:\code\mycode\python\PyRate\pyrate\scripts\gamma.py", line 210, in main
    parser.error(usage)
  File "C:\Python27\lib\optparse.py", line 1583, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "C:\Python27\lib\optparse.py", line 1573, in exit
    sys.exit(status)
SystemExit: 2

======================================================================
ERROR: test_with_roipac (pyrate.tests.system.system_test.SystemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\system\system_test.py", line 21, in test_with_roipac
    roipac.main()
  File "d:\code\mycode\python\PyRate\pyrate\scripts\roipac.py", line 261, in main
    parser.error(usage)
  File "C:\Python27\lib\optparse.py", line 1583, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "C:\Python27\lib\optparse.py", line 1573, in exit
    sys.exit(status)
SystemExit: 2

======================================================================
ERROR: test_multilook (pyrate.tests.prepifg_tests.PrepifgOutputTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\prepifg_tests.py", line 178, in test_multilook
    prepare_ifgs(self.ifgs, CUSTOM_CROP, xlooks, ylooks, thresh=1.0, user_exts=cext)
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 97, in prepare_ifgs
    return [warp(i, xlooks, ylooks, exts, res, thresh, verbose) for i in ifgs]
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 215, in warp
    data = _resample_ifg(ifg, cmd, x_looks, y_looks, thresh, md)
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 167, in _resample_ifg
    os.remove(tmp_path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\simon\\appdata\\local\\temp\\tmpyjpipi'

======================================================================
ERROR: test_same_size_multilooking (pyrate.tests.prepifg_tests.SameSizeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\prepifg_tests.py", line 287, in test_same_size_multilooking
    mlooked = prepare_ifgs(ifgs, ALREADY_SAME_SIZE, xlooks, ylooks)
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 97, in prepare_ifgs
    return [warp(i, xlooks, ylooks, exts, res, thresh, verbose) for i in ifgs]
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 215, in warp
    data = _resample_ifg(ifg, cmd, x_looks, y_looks, thresh, md)
  File "d:\code\mycode\python\PyRate\pyrate\prepifg.py", line 167, in _resample_ifg
    os.remove(tmp_path)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\simon\\appdata\\local\\temp\\tmpoxf5bg'

======================================================================
ERROR: <nose.suite.ContextSuite context=PyRateTests>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\suite.py", line 208, in run
    self.setUp()
  File "C:\Python27\lib\site-packages\nose\suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "C:\Python27\lib\site-packages\nose\suite.py", line 314, in setupContext
    try_run(context, names)
  File "C:\Python27\lib\site-packages\nose\util.py", line 470, in try_run
    return func()
  File "d:\code\mycode\python\PyRate\pyrate\tests\pyrate_tests.py", line 110, in setUpClass
    os.symlink(orig_dem, BASE_DEM_FILE)
AttributeError: 'module' object has no attribute 'symlink'

======================================================================
ERROR: test_cmd_dem (pyrate.tests.roipac_tests.RoipacCommandLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\roipac_tests.py", line 53, in test_cmd_dem
    roipac.main()
  File "d:\code\mycode\python\PyRate\pyrate\scripts\roipac.py", line 275, in main
    sys.exit('Error: no header/resource file given and -p option not specified')
SystemExit: Error: no header/resource file given and -p option not specified

======================================================================
ERROR: test_write (pyrate.tests.shared_tests.IfgIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\code\mycode\python\PyRate\pyrate\tests\shared_tests.py", line 157, in test_write
    os.remove(dest)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: '/tmp\\geo_060619-061002.tif'

======================================================================
FAIL: pyrate.tests.pyrate_tests.test_dest_ifg_paths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "d:\code\mycode\python\PyRate\pyrate\tests\pyrate_tests.py", line 74, in test_dest_ifg_paths
    assert dest_paths == ['out/ifg0.tif', 'out/ifg1.tif']
AssertionError

----------------------------------------------------------------------
Ran 157 tests in 6.198s

FAILED (errors=7, failures=1)
```
- The errors in _pyrate.tests.prepifg_tests.PrepifgOutputTests.test_multilook_ and _pyrate.tests.prepifg_tests.SameSizeTests.test_same_size_multilooking_ and (I think) _pyrate.tests.roipac_tests.RoipacCommandLine.test_cmd_dem_ and _pyrate.tests.shared_tests.IfgIOTests.test_write_ seem to be caused by what appears to be different behaviour of tempfile.mkstemp on windows and linux.
- The error in _pyrate.tests.roipac_tests.RoipacCommandLine.test_cmd_dem_ also occurs on the NCI (see #11).

**Comment by basaks** [comment]
Parked for now. Not supporting windows yet.
